### ISSUE TITLE
Darwin support?

### ISSUE THREAD

**Issue by apostasie** [fahedouch/go-logrotate#45]
Hey @fahedouch 

Was wondering if go-logrotate could be made to work for macOS?

From a distance and without actually trying it, it looks like just providing a `logrotate_darwin` that would be the same as the _linux variant would work?

LMK if this is something you would consider merging if there was a PR.

**Comment by fahedouch** [comment]
Hi @apostasie ,

`os.Chown`  is supported on  `osx` , so there is no blockers to enable `go-logrotate`on osx
